// Export all DTOs
export * from "./user/index.js";
export * from "./admissions/index.js";
export * from "./administration/index.js";
export * from "./course-design/index.js";
export * from "./resources/index.js";
export * from "./subject-selection/index.js";
export * from "./exams/index.js";
export * from "./academics/index.js";
export * from "./batches/index.js";
export * from "./library/index.js";
export * from "./fees/index.js";