version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file: 
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: backend-app
    restart: always
    env_file: /home/ubuntu/backend.env
    volumes:
      - /home/ubuntu/backend-logs:/logs
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./apps/frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - backend

volumes:
  postgres_data:
