import { SearchStudent } from "@/types/resources/SearchStudent"

export const studentData: SearchStudent[]=[
    {
        "serial_number": 1,
        "reg_number": "REG2024082501",
        "roll": "B-1001",
        "uid": "UID1001",
        "name": "Rahul Sharma",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Muslim",
        "category": "OBC",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Mathematics",
        "shift": "Afternoon",
        "status": "Dropped Out",
        "leaving_date": "2023-12-20"
    },
    {
        "serial_number": 2,
        "reg_number": "REG2024082502",
        "roll": "B-1002",
        "uid": "UID1002",
        "name": "Priya Verma",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Sikh",
        "category": "SC",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Chemistry",
        "shift": "Evening",
        "status": "Left",
        "leaving_date": "2024-06-15"
    },
    {
        "serial_number": 3,
        "reg_number": "REG2024082503",
        "roll": "B-1003",
        "uid": "UID1003",
        "name": "Amit Singh",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Christian",
        "category": "ST",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Biotechnology",
        "shift": "Night",
        "status": "Regular",
        "leaving_date": "2024-03-10"
    },
    {
        "serial_number": 4,
        "reg_number": "REG2024082504",
        "roll": "B-1004",
        "uid": "UID1004",
        "name": "Sana Khan",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Jain",
        "category": "General",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Computer Science",
        "shift": "Morning",
        "status": "Dropped Out",
        "leaving_date": "2024-05-20"
    },
    {
        "serial_number": 5,
        "reg_number": "REG2024082505",
        "roll": "B-1005",
        "uid": "UID1005",
        "name": "Rohan Patel",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Buddhist",
        "category": "OBC",
        "handicapped": "Yes",
        "course": "B.Com.",
        "specialization": "Accounting",
        "shift": "Afternoon",
        "status": "Left",
        "leaving_date": null
    },
    {
        "serial_number": 6,
        "reg_number": "REG2024082506",
        "roll": "B-1006",
        "uid": "UID1006",
        "name": "Meena Das",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Hindu",
        "category": "SC",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Finance",
        "shift": "Evening",
        "status": "Regular",
        "leaving_date": "2023-12-20"
    },
    {
        "serial_number": 7,
        "reg_number": "REG2024082507",
        "roll": "B-1007",
        "uid": "UID1007",
        "name": "Arjun Nair",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Muslim",
        "category": "ST",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Business Management",
        "shift": "Night",
        "status": "Dropped Out",
        "leaving_date": "2024-06-15"
    },
    {
        "serial_number": 8,
        "reg_number": "REG2024082508",
        "roll": "B-1008",
        "uid": "UID1008",
        "name": "Ritika Sen",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Sikh",
        "category": "General",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Marketing",
        "shift": "Morning",
        "status": "Left",
        "leaving_date": "2024-03-10"
    },
    {
        "serial_number": 9,
        "reg_number": "REG2024082509",
        "roll": "B-1009",
        "uid": "UID1009",
        "name": "Suresh Yadav",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Christian",
        "category": "OBC",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Taxation",
        "shift": "Afternoon",
        "status": "Regular",
        "leaving_date": "2024-05-20"
    },
    {
        "serial_number": 10,
        "reg_number": "REG2024082510",
        "roll": "B-1010",
        "uid": "UID1010",
        "name": "Neha Kapoor",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Jain",
        "category": "SC",
        "handicapped": "Yes",
        "course": "B.A.",
        "specialization": "History",
        "shift": "Evening",
        "status": "Dropped Out",
        "leaving_date": null
    },
    {
        "serial_number": 11,
        "reg_number": "REG2024082511",
        "roll": "B-1011",
        "uid": "UID1011",
        "name": "Vikram Chauhan",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Buddhist",
        "category": "ST",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "Political Science",
        "shift": "Night",
        "status": "Left",
        "leaving_date": "2023-12-20"
    },
    {
        "serial_number": 12,
        "reg_number": "REG2024082512",
        "roll": "B-1012",
        "uid": "UID1012",
        "name": "Pooja Mishra",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Hindu",
        "category": "General",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "English Literature",
        "shift": "Morning",
        "status": "Regular",
        "leaving_date": "2024-06-15"
    },
    {
        "serial_number": 13,
        "reg_number": "REG2024082513",
        "roll": "B-1013",
        "uid": "UID1013",
        "name": "Aniket Ghosh",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Muslim",
        "category": "OBC",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "Psychology",
        "shift": "Afternoon",
        "status": "Dropped Out",
        "leaving_date": "2024-03-10"
    },
    {
        "serial_number": 14,
        "reg_number": "REG2024082514",
        "roll": "B-1014",
        "uid": "UID1014",
        "name": "Simran Kaur",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Sikh",
        "category": "SC",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "Economics",
        "shift": "Evening",
        "status": "Left",
        "leaving_date": "2024-05-20"
    },
    {
        "serial_number": 15,
        "reg_number": "REG2024082515",
        "roll": "B-1015",
        "uid": "UID1015",
        "name": "Aditya Narayan",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Christian",
        "category": "ST",
        "handicapped": "Yes",
        "course": "B.Sc.",
        "specialization": "Physics",
        "shift": "Night",
        "status": "Regular",
        "leaving_date": null
    },
    {
        "serial_number": 16,
        "reg_number": "REG2024082516",
        "roll": "B-1016",
        "uid": "UID1016",
        "name": "Kavita Reddy",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Jain",
        "category": "General",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Mathematics",
        "shift": "Morning",
        "status": "Dropped Out",
        "leaving_date": "2023-12-20"
    },
    {
        "serial_number": 17,
        "reg_number": "REG2024082517",
        "roll": "B-1017",
        "uid": "UID1017",
        "name": "Tarun Mehta",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Buddhist",
        "category": "OBC",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Chemistry",
        "shift": "Afternoon",
        "status": "Left",
        "leaving_date": "2024-06-15"
    },
    {
        "serial_number": 18,
        "reg_number": "REG2024082518",
        "roll": "B-1018",
        "uid": "UID1018",
        "name": "Swati Joshi",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Hindu",
        "category": "SC",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Biotechnology",
        "shift": "Evening",
        "status": "Regular",
        "leaving_date": "2024-03-10"
    },
    {
        "serial_number": 19,
        "reg_number": "REG2024082519",
        "roll": "B-1019",
        "uid": "UID1019",
        "name": "Varun Thakur",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Muslim",
        "category": "ST",
        "handicapped": "No",
        "course": "B.Sc.",
        "specialization": "Computer Science",
        "shift": "Night",
        "status": "Dropped Out",
        "leaving_date": "2024-05-20"
    },
    {
        "serial_number": 20,
        "reg_number": "REG2024082520",
        "roll": "B-1020",
        "uid": "UID1020",
        "name": "Jasleen Kaur",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Sikh",
        "category": "General",
        "handicapped": "Yes",
        "course": "B.Com.",
        "specialization": "Accounting",
        "shift": "Morning",
        "status": "Left",
        "leaving_date": null
    },
    {
        "serial_number": 21,
        "reg_number": "REG2024082521",
        "roll": "B-1021",
        "uid": "UID1021",
        "name": "Karthik Iyer",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Christian",
        "category": "OBC",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Finance",
        "shift": "Afternoon",
        "status": "Regular",
        "leaving_date": "2023-12-20"
    },
    {
        "serial_number": 22,
        "reg_number": "REG2024082522",
        "roll": "B-1022",
        "uid": "UID1022",
        "name": "Neelam Kumari",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Jain",
        "category": "SC",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Business Management",
        "shift": "Evening",
        "status": "Dropped Out",
        "leaving_date": "2024-06-15"
    },
    {
        "serial_number": 23,
        "reg_number": "REG2024082523",
        "roll": "B-1023",
        "uid": "UID1023",
        "name": "Rajat Saxena",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Buddhist",
        "category": "ST",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Marketing",
        "shift": "Night",
        "status": "Left",
        "leaving_date": "2024-03-10"
    },
    {
        "serial_number": 24,
        "reg_number": "REG2024082524",
        "roll": "B-1024",
        "uid": "UID1024",
        "name": "Anusha Bhandari",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Hindu",
        "category": "General",
        "handicapped": "No",
        "course": "B.Com.",
        "specialization": "Taxation",
        "shift": "Morning",
        "status": "Regular",
        "leaving_date": "2024-05-20"
    },
    {
        "serial_number": 25,
        "reg_number": "REG2024082525",
        "roll": "B-1025",
        "uid": "UID1025",
        "name": "Gaurav Tiwari",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Muslim",
        "category": "OBC",
        "handicapped": "Yes",
        "course": "B.A.",
        "specialization": "History",
        "shift": "Afternoon",
        "status": "Dropped Out",
        "leaving_date": null
    },
    {
        "serial_number": 26,
        "reg_number": "REG2024082526",
        "roll": "B-1026",
        "uid": "UID1026",
        "name": "Shraddha Menon",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Sikh",
        "category": "SC",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "Political Science",
        "shift": "Evening",
        "status": "Left",
        "leaving_date": "2023-12-20"
    },
    {
        "serial_number": 27,
        "reg_number": "REG2024082527",
        "roll": "B-1027",
        "uid": "UID1027",
        "name": "Ravi Shukla",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Christian",
        "category": "ST",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "English Literature",
        "shift": "Night",
        "status": "Regular",
        "leaving_date": "2024-06-15"
    },
    {
        "serial_number": 28,
        "reg_number": "REG2024082528",
        "roll": "B-1028",
        "uid": "UID1028",
        "name": "Manisha Sinha",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Jain",
        "category": "General",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "Psychology",
        "shift": "Morning",
        "status": "Dropped Out",
        "leaving_date": "2024-03-10"
    },
    {
        "serial_number": 29,
        "reg_number": "REG2024082529",
        "roll": "B-1029",
        "uid": "UID1029",
        "name": "Kiran Pandey",
        "nationality": "Indian",
        "gender": "Female",
        "religion": "Buddhist",
        "category": "OBC",
        "handicapped": "No",
        "course": "B.A.",
        "specialization": "Economics",
        "shift": "Afternoon",
        "status": "Left",
        "leaving_date": "2024-05-20"
    },
    {
        "serial_number": 30,
        "reg_number": "REG2024082530",
        "roll": "B-1030",
        "uid": "UID1030",
        "name": "Harsh Vardhan",
        "nationality": "Indian",
        "gender": "Male",
        "religion": "Hindu",
        "category": "SC",
        "handicapped": "Yes",
        "course": "B.Sc.",
        "specialization": "Physics",
        "shift": "Evening",
        "status": "Regular",
        "leaving_date": null
    }
]