export * from "./app-module.model";
export * from "./department-designation-mapping.model"
export * from "./department.model";
export * from "./designation.model";
export * from "./user-group-domain.model";
export * from "./user-group-designation.model"
export * from "./user-group-member.model";
export * from "./user-group.model";
export * from "./user-privilege-sub-program-course.model"
export * from "./user-privilege-sub-scope.model"
export * from "./user-privilege-sub.model";
export * from "./user-privilege.model";
export * from "./user-staff-designation-mapping.model"
export * from "./user-status-reason.model";
export * from "./user-status-session-mapping.model";
export * from "./user-status.model";
export * from "./user-type.model";
