export * from "./access-group-application.model";
export * from "./access-group-designation.model";
export * from "./access-group-module-program-course-class.model";
export * from "./access-group-module-permission.model";
export * from "./access-group-module-program-course.model";
export * from "./access-group-module.model";
export * from "./access-group-user-type.model";
export * from "./access-group.model";
export * from "./app-module.model";
export * from "./department.model";
export * from "./designation.model";
export * from "./identity-master.model";
export * from "./institutional-role.model";
export * from "./session-status.model";
// export * from "./staff-designation.model";
export * from "./user-status-master.model";
export * from "./user-type.model";
