export * from "./addon.model";
export * from "./fees-component.model";
export * from "./fees-head.model";
export * from "./fees-receipt-type.model";
export * from "./fees-slab-mapping.model";
export * from "./fees-slab.model";
export * from "./fees-structure.model";
export * from "./instalment.model";
export * from "./student-fees-mapping.model";