CREATE TABLE "settlement_details" (
	"id" serial PRIMARY KEY NOT NULL,
	"payment_id_fk" integer NOT NULL,
	"transaction_id" varchar,
	"merchant_unique_ref" varchar,
	"transaction_date" varchar,
	"updated_date" varchar,
	"transaction_type" varchar,
	"status" varchar,
	"original_mid" varchar,
	"customer_id" varchar,
	"amount" varchar,
	"commission" varchar,
	"gst" varchar,
	"merchant_bill_id" varchar,
	"payout_id" varchar,
	"channel" varchar,
	"utr_number" varchar,
	"payout_date" varchar,
	"settled_date" varchar,
	"payment_mode" varchar,
	"issuing_bank" varchar,
	"settled_amount" varchar,
	"bank_transaction_id" varchar,
	"reference_transaction_id" varchar,
	"merchant_ref_id" varchar,
	"prn" varchar,
	"acquiring_fee" varchar,
	"platform_fee" varchar,
	"acquiring_tax" varchar,
	"platform_tax" varchar,
	"ifsc_code" varchar,
	"bank_name" varchar,
	"beneficiary_name" varchar,
	"masked_card_no" varchar,
	"card_network" varchar,
	"rrn_code" varchar,
	"dispute_id" varchar,
	"pos_id" varchar,
	"ext_serial_no" varchar,
	"gateway" varchar,
	"commission_rate" varchar,
	"product_code" varchar,
	"request_type" varchar,
	"fee_factor" varchar,
	"van" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "settlement_details_transaction_id_unique" UNIQUE("transaction_id")
);
--> statement-breakpoint
ALTER TABLE "settlement_details" ADD CONSTRAINT "settlement_details_payment_id_fk_payments_id_fk" FOREIGN KEY ("payment_id_fk") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;