-- Hand-authored 2026-08-07. NOT generated by drizzle-kit — a `generate` on
-- this branch produced a `0190_worried_ironclad.sql` that re-emitted the
-- entire documents module (rename + column adds already applied in 0175/
-- 0177/0178) because 12 meta snapshots are missing from
-- apps/backend/drizzle/meta/. Applying that autogen would fail every DB
-- with `relation "documents" does not exist` / `column already exists` /
-- constraint duplicate. This file replaces it with the ONLY genuinely new
-- object: the `document_batch_receipt_modes` join table + its enum + FK.
--
-- Fully idempotent — safe on any DB state (prod-cloned local, dev EC2,
-- fresh DB, previously-partially-applied). Guards mirror the hardened
-- pattern in 0187_docs_skipped_migration_repair.sql.

-- New enum. CREATE TYPE has no `IF NOT EXISTS`; DO block swallows the
-- duplicate_object exception on re-run.
DO $$ BEGIN
    CREATE TYPE "public"."document_batch_receipt_mode" AS ENUM(
        'EXAM_LINKED',
        'ADMINISTRATIVE'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- New table. CREATE TABLE IF NOT EXISTS is naturally idempotent.
CREATE TABLE IF NOT EXISTS "document_batch_receipt_modes" (
    "id" serial PRIMARY KEY NOT NULL,
    "document_batch_receipt_id_fk" integer NOT NULL,
    "mode" "public"."document_batch_receipt_mode" DEFAULT 'ADMINISTRATIVE' NOT NULL,
    "is_enabled" boolean DEFAULT false,
    "notify_student" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "document_batch_receipt_mode" UNIQUE ("document_batch_receipt_id_fk", "mode")
);--> statement-breakpoint

-- FK to `document_batch_receipts`. Guarded on parent-table existence so a
-- DB missing document_batch_receipts (e.g. dev EC2 with the 12-migration
-- gap) skips the FK rather than crashing the migration; the child table
-- still lands and the FK can be added by a later reconcile if needed.
-- Inner DO/EXCEPTION catches duplicate_object on re-run.
DO $$ BEGIN
    IF to_regclass('public.document_batch_receipts') IS NOT NULL THEN
        BEGIN
            ALTER TABLE "document_batch_receipt_modes"
                ADD CONSTRAINT "document_batch_receipt_modes_document_batch_receipt_id_fk_document_batch_receipts_id_fk"
                FOREIGN KEY ("document_batch_receipt_id_fk")
                REFERENCES "public"."document_batch_receipts"("id")
                ON DELETE NO ACTION ON UPDATE NO ACTION;
        EXCEPTION WHEN duplicate_object THEN NULL; END;
    END IF;
END $$;
