export type MarksheetTableType = {
  rollNumber: string;
  registrationNumber: string;
  name: string;
  uid: string;
  stream: string;
  framework: string;
  year1: number;
  year2: number;
  semester: string;
  theoryMarks: number;
  practicalMarks: number;
  internalMarks: number;
  subject: string;
  marksheetCode: string;
  vivalMarks: number;
  fullMarks: number;
  obtainedMarks: number;
  credit: number;
  sgpa: number;
  cgpa: number;
  letterGrade: string;
  remarks: string;
}; 