export * from "./academics";
export * from "./admissions";
export * from "./app";
export * from "./auth";
export * from "./course-design";
export * from "./fees";
export * from "./payments";
export * from "./resources";
export * from "./user";