export * from "./academics/index.js";
export * from "./admissions/index.js";
export * from "./app/index.js";
export * from "./auth/index.js";
export * from "./batches/index.js";
export * from "./course-design/index.js";
export * from "./fees/index.js";
export * from "./notifications/index.js";
export * from "./payments/index.js";
export * from "./process-control/index.js";
export * from "./resources/index.js";
export * from "./subject-selection/index.js";
export * from "./user/index.js";
export * from "./exams/index.js"
export * from "./administration/index.js"
export * from "./fees/index.js";