name: CI/CD Monorepo Production

on:
  push:
    branches:
      - aws_deployment  # Deploy only on aws_deployment branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            if [ ! -d "/workspace/academic360/.git" ]; then
              echo "Repo not found, cloning..."
              git clone -b aws_deployment https://github.com/datachef-lab/academic360
            fi

            cd /workspace/academic360
            git fetch --all
            git reset --hard origin/aws_deployment

            echo "Rebuilding & restarting services..."
            docker compose -f docker-compose.yml up -d --remove-orphans

            echo "Cleaning unused images..."
            docker image prune -f
