name: Log GitHub Activities to Google Sheets

on:
  push: # Logs commits
    branches:
      - main
  issues: # Logs all issue events
    types: [opened, edited, closed, labeled]
  pull_request: # Logs all PR events
    types: [opened, edited, closed]
  create: # Logs branch creation
  delete: # Logs branch deletion
  workflow_dispatch: # Allow manual triggering of the workflow via a button

jobs:
  log_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Log Activity to Google Sheets
        env:
          WEB_APP_URL: ${{ secrets.GOOGLE_SHEETS_WEBHOOK }}
        run: |
          # Determine the action type
          ACTION="${{ github.event.action || 'push' }}"

          # Debug: Print the action type
          echo "Action: $ACTION"

          # Determine the branch name
          if [[ "${ACTION}" == "push" || "${ACTION}" == "create" || "${ACTION}" == "delete" ]]; then
            BRANCH="${{ github.ref }}"  # Extract branch from ref for push/create/delete events
            BRANCH="${BRANCH#refs/heads/}"  # Remove "refs/heads/" prefix
          elif [[ "${ACTION}" == "pull_request" ]]; then
            BRANCH="${{ github.event.pull_request.head.ref }}"  # Extract branch for pull request source branch
          else
            BRANCH="N/A"  # No branch for issue events
          fi

          # Debug: Print the branch name
          echo "Branch: $BRANCH"

          # Determine the resource type
            if [[ "${ACTION}" == "push" || "${ACTION}" == "create" || "${ACTION}" == "delete" ]]; then
            RESOURCE="Branch"
            elif [[ "${ACTION}" == "pull_request" ]]; then
            RESOURCE="Pull Request"
            elif [[ "${ACTION}" == "issues" ]]; then
            RESOURCE="Issue"  # Explicitly set resource to "Issue" for any issue event
            fi

          # Debug: Print the resource and description

          echo "Description: $DESCRIPTION"

          # Determine the description for commits, PRs, or issues
          DESCRIPTION="${{ github.event.head_commit.message || github.event.pull_request.title || github.event.issue.title || 'No message' }}"

          echo "Action: $ACTION"
          echo "Resource: $RESOURCE"
          echo "Description: $DESCRIPTION"
          echo "Branch: $BRANCH"
          echo "User: ${{ github.actor }}"
          echo "Webhook URL: $WEB_APP_URL"

          # Send the data to Google Sheets
           curl -X POST -H "Content-Type: application/json" \
            -d "{\"action\": \"$ACTION\", \"user\": \"${{ github.actor }}\", \"description\": \"$DESCRIPTION\", \"branch\": \"$BRANCH\", \"resource\": \"$RESOURCE\"}" \
            "$WEB_APP_URL"
