name: Log GitHub Activities to Google Sheets

on:
  push: # Logs commits
    branches:
      - main
  issues: # Logs all issue events
    types: [opened, edited, closed, labeled]
  pull_request: # Logs all PR events
    types: [opened, edited, closed]
  create: # Logs branch creation
  delete: # Logs branch deletion
  workflow_dispatch: # Allow manual triggering of the workflow via a button

jobs:
  log_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Log Activity to Google Sheets
        env:
          WEB_APP_URL: ${{ secrets.GOOGLE_SHEETS_WEBHOOK }}
        run: |
          # Determine the action type
          ACTION="${{ github.event.action || 'push' }}"

          # Debug: Print the action type
          echo "Action: $ACTION"

          # Debug: Print the action type
          echo "Action: $ACTION"

          # Determine the branch name
          if [[ "${ACTION}" == "push" || "${ACTION}" == "create" || "${ACTION}" == "delete" ]]; then
            BRANCH="${{ github.ref }}"  # Extract branch from ref for push/create/delete events
            BRANCH="${BRANCH#refs/heads/}"  # Remove "refs/heads/" prefix
          elif [[ "${ACTION}" == "pull_request" ]]; then
            BRANCH="${{ github.event.pull_request.head.ref }}"  # Extract branch for pull request source branch
          else
            BRANCH="N/A"  # No branch for issue events
          fi

          # Debug: Print the branch name
          echo "Branch: $BRANCH"

          # Initialize resource type and description
          RESOURCE="Unknown"
          DESCRIPTION="No message"

          # Determine the branch name
          if [[ "${ACTION}" == "push" || "${ACTION}" == "create" || "${ACTION}" == "delete" ]]; then
            RESOURCE="Branch"
            BRANCH="${{ github.ref }}"  # Extract branch from ref for push/create/delete events
            BRANCH="${BRANCH#refs/heads/}"  # Remove "refs/heads/" prefix
            DESCRIPTION="Branch: $BRANCH"
          elif [[ "${ACTION}" == "pull_request" ]]; then
            RESOURCE="Pull Request"
            BRANCH="${{ github.event.pull_request.head.ref }}"  # Extract branch for PR source branch
            DESCRIPTION="PR Title: ${{ github.event.pull_request.title }} - Status: $ACTION"
          elif [[ "${ACTION}" == "issues" ]]; then
            if [[ "${{ github.event.issue.state }}" == "open" ]]; then
              RESOURCE="Issue"
              DESCRIPTION="Issue Opened: ${{ github.event.issue.title }}"
            elif [[ "${{ github.event.issue.state }}" == "closed" ]]; then
              RESOURCE="Issue"
              DESCRIPTION="Issue Closed: ${{ github.event.issue.title }}"
            elif [[ "${{ github.event.action }}" == "edited" ]]; then
              RESOURCE="Issue"
              DESCRIPTION="Issue Edited: ${{ github.event.issue.title }}"
            fi
          fi

          # Debug: Print the resource and description
          echo "Resource: $RESOURCE"
          echo "Description: $DESCRIPTION"

          # Send the data to Google Sheets
          curl -X POST -H "Content-Type: application/json" \
            -d "{
              \"action\": \"$ACTION\",
              \"user\": \"${{ github.actor }}\",
              \"description\": \"$DESCRIPTION\",
              \"resource\": \"$RESOURCE\"
              \"branch\": \"$BRANCH\"
            }" \
            $WEB_APP_URL
