name: Update Changelog

on:
  push:
    tags:
      - "v*" # Runs when a new tag is pushed

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify git-chglog installation
        run: |
          git-chglog --version

      - name: List files in the repository (debugging step)
        run: |
          ls -la

      - name: Install git-chglog
        run: |
          curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v0.15.3/git-chglog_linux_amd64.tar.gz | tar -xz
          mv git-chglog /usr/local/bin/

      - name: Generate Changelog
        run: |
          git-chglog --config .chglog/config.yml --output CHANGELOG.md

      - name: Commit and Push Changelog
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update Changelog for ${{ github.ref_name }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
